// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Answers an `invoke` from the page. */
	probeIpc: (sent: string) => __TAURI_INVOKE<Invoked>("probe_ipc", { sent }),
};

/* Types */
/**  A verdict and the evidence for it. */
export type Answer = {
	/**  What the probe found. */
	verdict: Verdict,
	/**
	 *  Why, in the words of whichever side found out. Empty when the verdict
	 *  says everything.
	 */
	detail: string,
};

/**
 *  The server's clock, as the page reads it once an animation frame.
 * 
 *  Strings and not numbers: the page paints these characters and formats
 *  nothing, so a unit only ever changes here.
 */
export type Clock = {
	/**  `M:SS.mmm`, the part anyone reads. */
	coarse: string,
	/**  The three microsecond digits after it, which are only ever a blur. */
	fine: string,
	/**  The counters beside it: frames drawn, throughput, where. */
	stats: Part[],
	/**
	 *  A round trip taken apart. On the page rather than behind a hover
	 *  because it is the only thing here that explains why a number the page
	 *  reports disagrees with the devtools network panel.
	 */
	breakdown: Part[],
};

/**  What a Tauri command saw when the page invoked it. */
export type Invoked = {
	/**
	 *  The token the page sent, back verbatim. Getting its own token back is
	 *  how the page knows the round trip carried an argument intact.
	 */
	echoed: string,
	/**
	 *  The label of the window the call came from.
	 * 
	 *  `tauri-plugin-topcoat` hangs a session on exactly this identity, so a
	 *  command that could not tell which window called it would sink the whole
	 *  arrangement.
	 */
	window: string,
};

/**  One labelled reading, in the gauges or in the breakdown. */
export type Part = {
	/**
	 *  What it is. Indented with spaces when it is a component of the line
	 *  above, which is why the column it lands in is `white-space: pre`.
	 */
	label: string,
	/**  The reading, already in whichever unit reads without a leading zero. */
	value: string,
	/**  Why it is not the same as the line above it. Empty when it is obvious. */
	note: string,
};

/**  One question the probe asks the webview. */
export type Probe = "page-origin" | "user-agent" | "gzip-decoded" | "es-module-loaded" | "resource-timing" | "fetch-post-body" | "fetch-post-headers" | "form-post-body" | "form-post-headers" | "set-cookie-returned" | "document-cookie" | "fetch-follows-303" | "navigation-follows-303" | "range-header-arrives" | "csp-document-rendered" | "csp-enforced" | "ipc-invoke" | "ipc-window-identity" | "ipc-invoke-under-csp" | "ipc-invoke-in-frame" | "local-storage" | "session-storage" | "indexed-db" | "foreign-document-ran" | "foreign-post-delivered" | "foreign-post-origin" | "foreign-post-referer";

/**  One line of the report, as the page receives it. */
export type Row = {
	/**  Which question this answers. */
	id: Probe,
	/**  How the row reads to whoever is looking at the report. */
	label: string,
	/**  What the probe found. */
	verdict: Verdict,
	/**
	 *  What it was expected to find. Equal to `verdict` on a webview this was
	 *  written against, and the point of the row when it is not.
	 */
	expected: Verdict,
	/**  Why. */
	detail: string,
};

/**
 *  The whole report, as the page receives it.
 * 
 *  The counts ride along rather than being derived on arrival, so the window
 *  and the terminal cannot come to different conclusions about how many of
 *  anything there were.
 */
export type Sheet = {
	/**  Every probe, in declaration order. */
	rows: Row[],
	/**  How the verdicts fell out: `13 yes, 8 no, 6 info`. */
	tally: string,
	/**
	 *  How many rows did not do what was expected, empty when none did. The
	 *  headline of a conformance run, and on a platform already measured it is
	 *  meant to stay empty.
	 */
	news: string,
};

/**  What a probe found. */
export type Verdict = 
/**  The webview behaved the way a real HTTP client would. */
"yes" | 
/**  It did not. */
"no" | 
/**  Neither: a value worth writing down. */
"info" | 
/**  Nothing established an answer either way. */
"unknown";

